"""sync exam_attempt answer schema

Revision ID: 37040bd42f36
Revises: d29f99ac75e5
Create Date: 2025-12-18 19:18:47.401817

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '37040bd42f36'
down_revision = 'd29f99ac75e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
