"""Add column source_document_ids on Exam and embedding on DocumentChunk

Revision ID: 3bf8ef35aef4
Revises: cfd522b832a4
Create Date: 2025-12-22 12:07:22.191412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3bf8ef35aef4'
down_revision = 'cfd522b832a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentchunk', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('exam', sa.Column('source_document_ids', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'source_document_ids')
    op.drop_column('documentchunk', 'embedding')
    # ### end Alembic commands ###
