"""cascade delete answer explanation

Revision ID: 3f1796cf23c3
Revises: 3bf8ef35aef4
Create Date: 2025-12-23 14:31:03.717160

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3f1796cf23c3'
down_revision = '3bf8ef35aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answerexplanation_answer_id_fkey'), 'answerexplanation', type_='foreignkey')
    op.create_foreign_key(None, 'answerexplanation', 'answer', ['answer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answerexplanation', type_='foreignkey')
    op.create_foreign_key(op.f('answerexplanation_answer_id_fkey'), 'answerexplanation', 'answer', ['answer_id'], ['id'])
    # ### end Alembic commands ###
