"""rename answer to correct_answer and enforce options

Revision ID: 60558614c134
Revises: 37040bd42f36
Create Date: 2025-12-19 13:06:06.894523

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60558614c134'
down_revision = '37040bd42f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'response',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('question', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.alter_column('question', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('question', 'answer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('question', 'options',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('question', 'correct_answer')
    op.alter_column('answer', 'response',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
