"""add answer explanation

Revision ID: cfd522b832a4
Revises: 60558614c134
Create Date: 2025-12-22 09:50:39.616974

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cfd522b832a4'
down_revision = '60558614c134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answerexplanation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('key_takeaway', sa.Text(), nullable=False),
    sa.Column('suggested_review', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answerexplanation_answer_id'), 'answerexplanation', ['answer_id'], unique=True)
    op.drop_column('answer', 'explanation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_answerexplanation_answer_id'), table_name='answerexplanation')
    op.drop_table('answerexplanation')
    # ### end Alembic commands ###
